### ISSUE TITLE
Server：バックエンド側の設定

### ISSUE THREAD

**Issue by Nozomuts** [kei-nishikawa48/Agora#7]
## 実装内容
- Node.js(Express.js)を使い、GraphQLを使用、MySQLとの接続を行う。

## 作業見積もり時間
- 5:00

## 納期
2020/10/24 23:00

**Comment by Nozomuts** [comment]
今日時間取れなそうなので明日中にやります

**Comment by kei-nishikawa48** [comment]
了解しました！無理しない程度にお願いします。
自分の方でもNode.js、Express、myspl、graphql等の知識を詰め込んでいくので
丸投げしちゃいましたが、理解できるようにはしときます
