### ISSUE TITLE
 Error: Not authenticated as userの改善

### ISSUE THREAD

**Issue by kei-nishikawa48** [kei-nishikawa48/Agora#86]
## 実装内容

*  Error: Not authenticated as userの改善
* 原因を特定してエラーを出ないようにして欲しいです。
## 作業時間(目安)

* 

## 納期

* 

## メモ・参考資料

*

**Comment by Nozomuts** [comment]
@kei-nishikawa48 
原因特定しました！
できる時とできない時があるのはリロードしてるかしてないかでした（多分）。↓のコード的にloginとかしても_app.tsxが再レンダリングされないので、headersにtokenが入らない感じです。だからリロードしたら再レンダリングされてtokenが入るのでうまくいくぽい

改善方法としては、
* リロードを入れるようにする
* 送信する時にheaderに直に入れる
* 無理やり再レンダリングさせる
リロードが意外と良いかもしれません、2つ目はないな


https://github.com/kei-nishikawa48/proshare/blob/b07cb3016ba675402b798c58cd5f5f70056f64e6/pages/_app.tsx#L32-L43

**Comment by kei-nishikawa48** [comment]
なるほど、token情報が変わった時にレンダリングまたはリロードが良さそうですね。
どちらかで実装をお願いします！
